name: Build iOS app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    # Only run build in template repo
    if: github.event.repository.name == 'KMP-App-Template' && github.repository_owner == 'LeoAndo'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Create local.properties
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "GITHUB_ACCESS_TOKEN=GITHUB_ACCESS_TOKEN" >> local.properties
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      - name: Copy Config.xcconfig.sample to Config.xcconfig
        run: cp iosApp/Configuration/Config.xcconfig.sample iosApp/Configuration/Config.xcconfig
      - name: Add Access Token to Config.xcconfig
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "GITHUB_ACCESS_TOKEN=GITHUB_ACCESS_TOKEN" >> iosApp/Configuration/Config.xcconfig
      - name: iOS debug build
        run: cd iosApp && xcodebuild -scheme iosApp -configuration Debug -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' CODE_SIGNING_ALLOWED='NO'
